# Generated by Django 3.0 on 2019-12-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='postStuff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('userName', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=400)),
                ('img', models.ImageField(upload_to='profile')),
                ('attachment', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
