# Generated by Django 3.0 on 2019-12-12 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postingApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poststuff',
            name='text',
            field=models.TextField(max_length=400),
        ),
    ]
