# Generated by Django 3.0 on 2019-12-12 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postingApp', '0002_auto_20191212_1139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poststuff',
            old_name='userName',
            new_name='username',
        ),
    ]
