# Generated by Django 3.0 on 2019-12-12 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postingApp', '0003_auto_20191212_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='poststuff',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postingApp.User'),
        ),
    ]
