# Generated by Django 3.0 on 2019-12-17 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('postingApp', '0006_auto_20191212_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='profilePic')),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='poststuff',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='poststuff',
            name='img',
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postingApp.PostStuff'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=400),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_teacher', models.BooleanField(default=False)),
                ('is_student', models.BooleanField(default=False)),
                ('is_consulter', models.BooleanField(default=False)),
                ('is_moavenP', models.BooleanField(default=False)),
                ('is_moavenA', models.BooleanField(default=False)),
                ('is_moavenE', models.BooleanField(default=False)),
                ('is_parent', models.BooleanField(default=False)),
                ('is_principle', models.BooleanField(default=False)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postingApp.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attach', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postingApp.PostStuff')),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postingApp.Profile'),
        ),
        migrations.AlterField(
            model_name='poststuff',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postingApp.Profile'),
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('post', 'author')},
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='approved_comment',
        ),
    ]
