# Generated by Django 3.0 on 2019-12-12 16:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('postingApp', '0007_auto_20191212_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poststuff',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='poststuff',
            name='img',
        ),
        migrations.AddField(
            model_name='user',
            name='img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postingApp.PostStuff'),
        ),
        migrations.CreateModel(
            name='attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attach', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postingApp.PostStuff')),
            ],
        ),
    ]
