# Generated by Django 3.0.5 on 2020-05-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='Profile',
            name='mom_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='Profile',
            name='dad_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]